# Generated by Django 5.2.17 on 2026-09-10 18:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=140, verbose_name='nome do cliente')),
                ('legal_name', models.CharField(blank=True, max_length=180, verbose_name='razão social / nome completo')),
                ('tax_id', models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='CPF / CNPJ')),
                ('kind', models.CharField(choices=[('store', 'Loja / comércio'), ('service', 'Prestador de serviços'), ('other', 'Outro')], default='store', max_length=12, verbose_name='tipo')),
                ('status', models.CharField(choices=[('lead', 'Em negociação'), ('active', 'Ativo'), ('paused', 'Pausado'), ('inactive', 'Inativo')], default='active', max_length=12, verbose_name='status')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='pessoa de contato')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=24, verbose_name='telefone')),
                ('address', models.TextField(blank=True, verbose_name='endereço')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('trade_name',),
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='nome do contrato / pacote')),
                ('start_date', models.DateField(verbose_name='início')),
                ('end_date', models.DateField(verbose_name='término')),
                ('monthly_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor mensal')),
                ('billing_day', models.PositiveSmallIntegerField(default=10, verbose_name='dia de vencimento')),
                ('terms', models.TextField(verbose_name='termos do contrato')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado para assinatura'), ('signed', 'Assinado'), ('cancelled', 'Cancelado')], default='draft', max_length=12, verbose_name='status')),
                ('signature_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signer_name', models.CharField(blank=True, max_length=160, verbose_name='nome do signatário')),
                ('signer_tax_id', models.CharField(blank=True, max_length=24, verbose_name='CPF do signatário')),
                ('signer_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do signatário')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='assinado em')),
                ('signature_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da assinatura')),
                ('signature_user_agent', models.CharField(blank=True, max_length=300, verbose_name='navegador da assinatura')),
                ('signature_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='comprovante criptográfico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='agency.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'ordering': ('-start_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ContentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('story', 'Stories'), ('feed', 'Feed'), ('video', 'Vídeo'), ('reel', 'Reels'), ('article', 'Matéria no portal'), ('banner', 'Banner'), ('other', 'Outro')], max_length=12, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='material')),
                ('scheduled_for', models.DateField(verbose_name='data prevista')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('status', models.CharField(choices=[('planned', 'Planejado'), ('production', 'Em produção'), ('approval', 'Aguardando aprovação'), ('published', 'Publicado'), ('cancelled', 'Cancelado')], default='planned', max_length=12, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='agency.contract', verbose_name='contrato')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'ordering': ('scheduled_for', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Entrada'), ('expense', 'Saída')], max_length=8, verbose_name='tipo')),
                ('description', models.CharField(max_length=180, verbose_name='descrição')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='data do pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], default='pending', max_length=10, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='agency.client', verbose_name='cliente')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_entries', to='agency.contract', verbose_name='contrato')),
            ],
            options={
                'verbose_name': 'lançamento financeiro',
                'verbose_name_plural': 'lançamentos financeiros',
                'ordering': ('-due_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DeliverableQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('story', 'Stories'), ('feed', 'Feed'), ('video', 'Vídeo'), ('reel', 'Reels'), ('article', 'Matéria no portal'), ('banner', 'Banner'), ('other', 'Outro')], max_length=12, verbose_name='tipo de material')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantidade mensal')),
                ('notes', models.CharField(blank=True, max_length=180, verbose_name='detalhes')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='agency.contract', verbose_name='contrato')),
            ],
            options={
                'verbose_name': 'item do pacote',
                'verbose_name_plural': 'itens do pacote',
                'ordering': ('kind',),
                'constraints': [models.UniqueConstraint(fields=('contract', 'kind'), name='unique_quota_per_contract_kind')],
            },
        ),
    ]
