# Generated by Django 5.2.17 on 2026-09-10 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome do modelo')),
                ('content', models.TextField(help_text='Variáveis disponíveis: [[cliente_nome]], [[cliente_razao_social]], [[cliente_documento]], [[cliente_endereco]], [[contrato_nome]], [[data_inicio]], [[data_fim]], [[valor_mensal]], [[dia_vencimento]] e [[pacote_mensal]].', verbose_name='conteúdo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'modelo de contrato',
                'verbose_name_plural': 'modelos de contrato',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='agency.contracttemplate', verbose_name='modelo utilizado'),
        ),
    ]
