# Generated by Django 5.2.17 on 2026-09-11 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_financialentry_counterparty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Portal Verdade Ceará', max_length=100, verbose_name='nome exibido')),
                ('legal_name', models.CharField(blank=True, max_length=180, verbose_name='razão social')),
                ('tax_id', models.CharField(blank=True, max_length=24, verbose_name='CPF / CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail institucional')),
                ('phone', models.CharField(blank=True, max_length=24, verbose_name='telefone')),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='endereço')),
                ('city', models.CharField(default='Fortaleza / CE', max_length=100, verbose_name='cidade / UF')),
                ('accent_color', models.CharField(default='#c71927', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Informe uma cor hexadecimal válida.')], verbose_name='cor de destaque')),
                ('default_theme', models.CharField(choices=[('dark', 'Escuro'), ('light', 'Claro')], default='dark', max_length=8, verbose_name='tema padrão')),
                ('density', models.CharField(choices=[('compact', 'Compacto'), ('comfortable', 'Confortável')], default='compact', max_length=12, verbose_name='tamanho da interface')),
                ('logo', models.ImageField(blank=True, upload_to='branding/', verbose_name='logo institucional')),
                ('pdf_footer', models.CharField(blank=True, max_length=100, verbose_name='rodapé dos documentos')),
            ],
            options={
                'verbose_name': 'configuração da empresa',
                'verbose_name_plural': 'configurações da empresa',
            },
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='content',
            field=models.TextField(help_text='Variáveis disponíveis: [[cliente_nome]], [[cliente_razao_social]], [[cliente_documento]], [[cliente_endereco]], [[contrato_nome]], [[data_inicio]], [[data_fim]], [[valor_mensal]], [[dia_vencimento]] e [[pacote_mensal]]. Dados da empresa: [[empresa_nome]], [[empresa_razao_social]], [[empresa_documento]], [[empresa_endereco]], [[empresa_email]], [[empresa_telefone]], [[empresa_cidade]].', verbose_name='conteúdo'),
        ),
    ]
