# Generated by Django 5.2.17 on 2026-09-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_organizationsettings_alter_contracttemplate_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialentry',
            name='billing_month',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='competência gerada pelo contrato'),
        ),
        migrations.AddConstraint(
            model_name='financialentry',
            constraint=models.UniqueConstraint(fields=('contract', 'billing_month'), name='unique_contract_billing_month'),
        ),
    ]
