# Generated by Django 5.2.17 on 2026-09-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_personalizable_default_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='compact_logo',
            field=models.ImageField(blank=True, upload_to='branding/', verbose_name='logo compacta (símbolo)'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='panel_logo',
            field=models.CharField(choices=[('full', 'Inteira'), ('compact', 'Compacta')], default='full', max_length=8, verbose_name='logo exibida no painel'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='permissões por módulo'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='branding/', verbose_name='logo inteira'),
        ),
    ]
